### ISSUE TITLE
Minoshroom Axe, Knightly Axe and Knightly Sword do not do advertised Extra Damage!

### ISSUE THREAD

**Issue by GregoriusT** [GTNewHorizons/twilightforest#30]
While searching for how much extra Damage the Axe does when charging I found that the +3.5 Hearts of extra damage are never applied to anything because the following function is never called.

https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/twilightforest/item/ItemTFMinotaurAxe.java#L68

And instead the private variable is used to calculate Damage

https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/twilightforest/item/ItemTFMinotaurAxe.java#L117-L119

And yes I tested that in world too. No Extra Damage at all.

Edit: Same applies to Knightly Weapons just that THOSE have their Code for the +1 Heart of Damage commented out entirely.

https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/twilightforest/item/ItemTFKnightlySword.java#L70-L88
https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/twilightforest/item/ItemTFKnightlyAxe.java#L77-L94

**Comment by Gordon-Frohman** [comment]
Fixed all of this in my PR
