### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by unilock** [GTNewHorizons/twilightforest#45]
A client-side class is being loaded server-side here:

https://github.com/GTNewHorizons/twilightforest/blob/ef82996cddaeab9b579d740fb382cc15be6ae44d/src/main/java/twilightforest/integration/TFTinkerConstructIntegration.java#L838-L849

Namely `net.minecraft.client.Minecraft`.

**Comment by Gordon-Frohman** [comment]
Will have to write a ClientProxy for it, I guess
