### ISSUE TITLE
Add compatibility with Skinport Unofficial

### ISSUE THREAD

**Issue by Omgise** [GTNewHorizons/twilightforest#67]
If you use [Skinport Unofficial] (https://github.com/RetroForge/SkinPort) ，Giants will not display skins correctly.

![屏幕截图 2024-05-07 085647](https://github.com/GTNewHorizons/twilightforest/assets/106000018/52470827-8339-416e-9392-1d0fd1165b1a)

**Comment by DrParadox7** [comment]
It looks fine to me 🤔

**Comment by Omgise** [comment]
> It looks fine to me 🤔

Although the skin is displayed normally, it shows the default Alex skin, not the skin of my Microsoft account.
