### ISSUE TITLE
Naga Crash

### ISSUE THREAD

**Issue by N2K2021** [GTNewHorizons/twilightforest#71]
Version 2.5.1
Edit: Twilight Version 2.6.9

[crash-2024-05-14_14.59.02-server.txt](https://github.com/GTNewHorizons/twilightforest/files/15310453/crash-2024-05-14_14.59.02-server.txt)

**Comment by Lyfts** [comment]
Fixed in https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12
