### ISSUE TITLE
Game Randomly Crashes When Exploring Twilight Forest 

### ISSUE THREAD

**Issue by FGBullZz** [GTNewHorizons/twilightforest#94]
### Mod Version

2.5.25

### Bug Report

https://mclo.gs/9bzKl6Q is the crash report, this same thing happened once before and i went to a previous backup and replicated what happened during the crash. I dont want to have to keep going back to a new backup every time I enter the twilight forest 

### Java Version

Java 8

### Mod List or GTNH Pack Version

2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by FourIsTheNumber** [comment]
Duplicate of dozens of tickets across this repo and the main issue tracker. Update the twilight forest mod.

**Comment by wlhlm** [comment]
Here is the link: https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar
